version: "3.8"

services:
  jekyll:
    build: .
    ports:
      - "4000:4000"
      - "35729:35729" # порт для LiveReload
    volumes:
      # Монтируем папку с блогом (текущую директорию)
      - ./:/srv/jekyll
      # Исключаем служебные папки Jekyll чтобы избежать проблем с правами
      - /srv/jekyll/_site
      - /srv/jekyll/.jekyll-cache
    environment:
      - JEKYLL_ENV=development
